spring:
  application:
    name: jewelrystore
  datasource:
    url: jdbc:sqlserver://localhost\\LAPTOP-F98VSAGL:1433;databaseName=StoreManager;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nightfury455@gmail.com
    password: qakfjurwmabkteza
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

fileUpload:
  promotionPath: Promotion/
  productPath: Product/
  userPath: User/
server:
  error:
    path: /error
firebase:
  config:
    path: /firebase-service-account.json
  bucket-name: jewelrystore-2ks1dotnet.appspot.com
  img-url: https://storage.googleapis.com/${firebase.bucket-name}/

jwt:
  privateKey: wQwCoOrdAU3iyXZsqshyOKiC2xzW9C7R+/3HjwQ2cEk=
