spring:
  application:
    name: jewelrystore
  datasource:
    url: jdbc:sqlserver://localhost\\LAPTOP-F98VSAGL:1433;databaseName=StoreManager;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB

fileUpload:
  promotionPath: Promotion/
  productPath: Product/
  userPath: User/
server:
  error:
    path: /error
firebase:
  config:
    path: /firebase-service-account.json
  bucket-name: jewelrystore-2ks1dotnet.appspot.com
  img-url: https://storage.googleapis.com/${firebase.bucket-name}/

jwt:
  privateKey: wQwCoOrdAU3iyXZsqshyOKiC2xzW9C7R+/3HjwQ2cEk=


payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: OSJWY5E5
    secretKey: RZ9X5FM7S4799PB3DIU0GOBIFMYC3ZGQ
    returnUrl: http://localhost:8080/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
    tokenUrl: https://sandbox.vnpayment.vn/token_ui/create-token.html