spring:
  application:
    name: jewelrystore
  datasource:
    url: jdbc:sqlserver://localhost\\LAPTOP-F98VSAGL:1433;databaseName=StoreManager;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB

fileUpload:
  rootPath: D:\UploadImage
server:
  error:
    path: /error

jwt:
  privateKey: wQwCoOrdAU3iyXZsqshyOKiC2xzW9C7R+/3HjwQ2cEk=
