spring:
  application:
    name: jewelrystore
  datasource:
    url: jdbc:sqlserver://store-manager.ch2a2i4kg4ty.us-east-1.rds.amazonaws.com:1433;databaseName=MyDatabase;encrypt=true;trustServerCertificate=true
    username: admin
    password: Strongbow22
