spring:
  application:
    name: jewelrystore
  datasource:
    url: jdbc:sqlserver://localhost\\LAPTOP-F98VSAGL:1433;databaseName=StoreManager;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB

fileUpload:
  rootPath: C:\Users\Acer\Desktop\UploadImage
