spring:
  profiles:
    active: local
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2ks1dotnet@gmail.com
    password: oxzpcgzbjopyhvmu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

fileUpload:
  promotionPath: Promotion/
  productPath: Product/
  userPath: User/
server:
  error:
    path: /error
firebase:
  config:
    path: /firebase-service-account.json
  bucket-name: jewelrystore-2ks1dotnet.appspot.com
  img-url: https://storage.googleapis.com/${firebase.bucket-name}/

jwt:
  privateKey: wQwCoOrdAU3iyXZsqshyOKiC2xzW9C7R+/3HjwQ2cEk=

rateEarnPoint:
  rate: 100000

invoiceID:
  Sell: 1
  Imports: 2
  BuyBack: 3

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: OSJWY5E5
    secretKey: RZ9X5FM7S4799PB3DIU0GOBIFMYC3ZGQ
    returnUrl: http://127.0.0.1:5500/src/main/resources/templates/dist/InvoiceDefault.html
    version: 2.1.0
    command: pay
    orderType: other

apiURL: /api
